### ISSUE TITLE
cannot find package "github.com/google/go-github/v28/github"

### ISSUE THREAD

**Issue by hugovk** [micnncim/label-exporter#4]
Following the README instructions, I get this:

```console
$ go get github.com/micnncim/label-exporter/cmd/label-exporter
package github.com/google/go-github/v28/github: cannot find package "github.com/google/go-github/v28/github" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/github.com/google/go-github/v28/github (from $GOROOT)
	/Users/hugo/go/src/github.com/google/go-github/v28/github (from $GOPATH)
$ go version
go version go1.10.3 darwin/amd64
```

Do I need to install some dependencies first? Or can the dependencies be also installed by this tool?

**Comment by micnncim** [comment]
Build of this tool requires to use Go modules. You need to install and use  Go 1.13 or later if you want to build this tool.

I created binary releases so you can check out these assets without any build.

See: https://github.com/micnncim/label-exporter/releases

**Comment by hugovk** [comment]
Thanks, running that says:

```
2020/02/27 17:37:15 missing GITHUB_TOKEN
```

Should I create one at https://github.com/settings/tokens/new and set it as an `GITHUB_TOKEN` env var? And what are the minimum scopes needed?

**Comment by micnncim** [comment]
Yes, you should create a token with public_repo as a scope.

**Comment by hugovk** [comment]
Thanks, that worked! I've created PR https://github.com/micnncim/label-exporter/pull/6 to update the README instructions.
